### ISSUE TITLE
Number Not displaying on top of Gauge 

### ISSUE THREAD

**Issue by Waqar06** [bernii/gauge.js#243]
The number not displaying on top of the gauge 
![guage](https://user-images.githubusercontent.com/37383053/126053345-1aadc076-61fd-465b-92be-31ba2f97547f.JPG)
as shows in the demo.

**Comment by austenstone** [comment]
The demo uses a div to show the number.

```html
<div id="preview-textfield" style="font-size: 24px;">1,250</div>
```

```css
#preview-textfield {
    position: absolute;
    top: 65px;
    left: 0;
    right: 0;
    text-align: center;
    font-size: 2em;
    font-weight: bold;
    color: black;
    font-family: 'Amaranth', sans-serif;
}
```

```js
gauge.setTextField(document.getElementById("preview-textfield"));
```

The gauge should now update the field for you.

```js
BaseGauge.prototype.setTextField = function(textField, fractionDigits) {
    return this.textField = textField instanceof TextRenderer ? textField : new TextRenderer(textField, fractionDigits);
};
```
